// angular/src/app/components/file-input/file-input.ts
import {
  Component,
  ChangeDetectionStrategy,
  ElementRef,
  effect,
  input,
  output,
  viewChild,
} from '@angular/core';

/**
 * Native file picker with a "clear" button. Syncs the native input's file
 * list when the bound File signal changes, so the visible filename stays
 * in sync when a file is dropped elsewhere.
 */
@Component({
  selector: 'app-file-input',
  standalone: true,
  templateUrl: './file-input.html',
  styleUrl: './file-input.scss',
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class FileInput {
  readonly file = input<File | null>(null);
  readonly fileChange = output<File | null>();

  protected readonly inputRef = viewChild.required<ElementRef<HTMLInputElement>>('nativeInput');

  constructor() {
    effect(() => {
      const el = this.inputRef().nativeElement;
      const file = this.file();
      if (file) {
        if (el.files && el.files.length === 1 && el.files[0] === file) return;
        try {
          const dt = new DataTransfer();
          dt.items.add(file);
          el.files = dt.files;
        } catch {
          // Older browsers may block; ignore.
        }
      } else if (el.value) {
        el.value = '';
      }
    });
  }

  onChange(e: Event): void {
    const el = e.target as HTMLInputElement;
    this.fileChange.emit(el.files?.[0] ?? null);
  }

  clear(): void {
    this.fileChange.emit(null);
  }
}

// web/src/ui/FileInput.tsx
import { useEffect, useRef } from "react";

export function FileInput({
  file,
  onFile,
}: {
  file: File | null;
  onFile: (f: File | null) => void;
}) {
  const inputRef = useRef<HTMLInputElement>(null);

  useEffect(() => {
    const el = inputRef.current;
    if (!el) return;
    if (file) {
      if (el.files && el.files.length === 1 && el.files[0] === file) return;
      try {
        const dt = new DataTransfer();
        dt.items.add(file);
        el.files = dt.files;
      } catch {
        // Older browsers may block programmatic FileList assignment; ignore.
      }
    } else if (el.value) {
      el.value = "";
    }
  }, [file]);

  return (
    <div className="flex items-center gap-3">
      <input
        ref={inputRef}
        type="file"
        accept="image/png,image/jpeg,image/webp"
        onChange={(e) => onFile(e.target.files?.[0] ?? null)}
        className="block text-sm file:mr-3 file:py-1.5 file:px-3 file:rounded-md file:border-0 file:bg-slate-100 file:text-slate-700 hover:file:bg-slate-200"
      />
      {file && (
        <button
          type="button"
          onClick={() => onFile(null)}
          className="text-xs text-slate-500 hover:text-slate-700"
        >
          clear
        </button>
      )}
    </div>
  );
}
