// angular/src/app/components/cover-preview-separate/cover-preview-separate.ts
import {
  Component,
  ChangeDetectionStrategy,
  ElementRef,
  computed,
  effect,
  input,
  output,
  signal,
  viewChild,
} from '@angular/core';
import type {
  BorderMode,
  CasePreset,
  FitMode,
  SpinePresetId,
  SpineTextAlign,
} from '@core/types';
import { SectionImage } from '../section-image/section-image';
import { DropOverlay } from '../drop-overlay/drop-overlay';
import { SpinePresetPreview } from '../spine-preset-preview/spine-preset-preview';
import { borderPreviewPx, computeStageLayout } from '../../utils/stage-layout';
import { MM_PER_INCH } from '../../pdf/layout';
import {
  getSpinePresetImageAspectRatio,
  getSpinePresetImageUrl,
  type SpinePresetImageKey,
} from '../../spine/assets';

/**
 * Three-section preview (back / spine / front). Also overlays the spine
 * preset's front-cover top image when applicable (ps2/xbox), including
 * the widening padding and PS2 white separator.
 */
@Component({
  selector: 'app-cover-preview-separate',
  standalone: true,
  imports: [SectionImage, DropOverlay, SpinePresetPreview],
  templateUrl: './cover-preview-separate.html',
  styleUrl: './cover-preview-separate.scss',
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class CoverPreviewSeparate {
  readonly preset = input.required<CasePreset>();
  readonly fit = input.required<FitMode>();
  readonly borderMode = input<BorderMode>('none');
  readonly borderThicknessPx = input<number>(0);
  readonly borderColor = input<string>('#000000');
  readonly fitBackground = input<string>('#000000');
  readonly dpi = input<number>(300);

  readonly backUrl = input<string | null>(null);
  readonly frontUrl = input<string | null>(null);
  readonly spineUrl = input<string | null>(null);
  readonly spinePreset = input.required<SpinePresetId>();
  readonly spineTitle = input<string>('');
  readonly spineBg = input<string>('#ffffff');
  readonly spineTextColor = input<string>('#000000');
  readonly spineTextAlign = input<SpineTextAlign>('center');
  readonly showFrontPresetImage = input<boolean>(true);
  readonly frontImageWidening = input<number>(0);
  readonly showFrontSeparator = input<boolean>(true);
  readonly isDraggingFile = input<boolean>(false);

  readonly backSelected = output<File | null>();
  readonly frontSelected = output<File | null>();
  readonly spineSelected = output<File | null>();

  private readonly wrapRef = viewChild.required<ElementRef<HTMLDivElement>>('wrap');
  private readonly labelsRef = viewChild.required<ElementRef<HTMLDivElement>>('labels');
  private readonly containerSize = signal({ width: 0, height: 0 });
  private readonly labelsSize = signal({ width: 0, height: 0 });

  protected readonly layout = computed(() =>
    computeStageLayout(
      this.preset(),
      this.containerSize().width,
      this.containerSize().height,
      this.labelsSize().height,
    ),
  );
  protected readonly borderPx = computed(() =>
    borderPreviewPx(
      this.borderMode(),
      this.borderThicknessPx(),
      this.layout().mmToPx,
      this.dpi(),
    ),
  );
  protected readonly outerShadow = computed(() => {
    const px = this.borderPx();
    return px > 0 && this.borderColor()
      ? `0 0 0 ${px}px ${this.borderColor()}`
      : 'none';
  });
  protected readonly gridTemplateCols = computed(() => {
    const p = this.preset();
    const side = (p.totalWidthMm - p.spineWidthMm) / 2;
    return `${side}fr ${p.spineWidthMm}fr ${side}fr`;
  });

  protected readonly frontTopImage = computed(() => {
    const p = this.spinePreset();
    if (!this.showFrontPresetImage()) return null;
    if (p !== 'ps2' && p !== 'xbox') return null;
    const key = p as SpinePresetImageKey;
    const layout = this.layout();
    const sideWidthMm = layout.sideWidthMm;
    const sideWidthPx = layout.sideWidthPx;
    const ar = getSpinePresetImageAspectRatio(key, 'front');
    const scale = sideWidthPx / ((sideWidthMm * this.dpi()) / MM_PER_INCH);
    const wideningPx = this.frontImageWidening() > 0 ? this.frontImageWidening() * scale : 0;
    const separatorPx =
      key === 'ps2' && this.showFrontSeparator() ? Math.max(1, 4 * scale) : 0;
    const imgHeightPx = sideWidthPx / ar;
    const blockHeightPx = imgHeightPx + wideningPx * 2;
    return {
      url: getSpinePresetImageUrl(key, 'front'),
      wideningPx,
      separatorPx,
      imgHeightPx,
      blockHeightPx,
    };
  });

  constructor() {
    effect((onCleanup) => {
      const wrap = this.wrapRef().nativeElement;
      const labels = this.labelsRef().nativeElement;
      const update = () => {
        this.containerSize.set({ width: wrap.clientWidth, height: wrap.clientHeight });
        this.labelsSize.set({ width: labels.clientWidth, height: labels.clientHeight });
      };
      update();
      const wo = new ResizeObserver(update);
      const lo = new ResizeObserver(update);
      wo.observe(wrap);
      lo.observe(labels);
      onCleanup(() => {
        wo.disconnect();
        lo.disconnect();
      });
    });
  }
}

// web/src/components/CoverPreviewSeparate.tsx
import { useObjectUrl } from "../hooks/useObjectUrl";
import { useCoverStage } from "../hooks/useCoverStage";
import { SectionImage } from "./SectionImage";
import { SpinePresetPreview } from "./SpinePresetPreview";
import { DropOverlay } from "../ui/DropOverlay";
import { getSpinePresetImageUrl, getSpinePresetImageAspectRatio, type SpinePresetImageKey } from "../spine/assets";
import type { BorderMode, CasePreset, Fit, SpinePreset, SpineTextAlign } from "../types";

interface Props {
  preset: CasePreset;
  fit: Fit;
  borderMode: BorderMode;
  borderThicknessPx: number;
  borderColor: string;
  fitBackground: string;
  dpi: number;

  backImage: File | null;
  frontImage: File | null;
  spineImage: File | null;
  spinePreset: SpinePreset;
  spineTitle: string;
  spineBg: string;
  spineTextColor: string;
  spineTextAlign: SpineTextAlign;
  showFrontPresetImage: boolean;
  frontImageWidening: number;
  showFrontSeparator: boolean;

  onSelectBack?: (file: File | null) => void;
  onSelectFront?: (file: File | null) => void;
  onSelectSpine?: (file: File | null) => void;
  isDraggingFile?: boolean;
}

const MM_PER_INCH = 25.4;

export function CoverPreviewSeparate(props: Props) {
  const {
    preset,
    fit,
    borderMode,
    borderThicknessPx,
    borderColor,
    fitBackground,
    dpi,
    backImage,
    frontImage,
    spineImage,
    spinePreset,
    spineTitle,
    spineBg,
    spineTextColor,
    spineTextAlign,
    showFrontPresetImage,
    frontImageWidening,
    showFrontSeparator,
    onSelectBack,
    onSelectFront,
    onSelectSpine,
    isDraggingFile,
  } = props;

  const { wrapRef, labelsRef, stageWidth, stageHeight, mmToPx, padding } =
    useCoverStage(preset);
  const backUrl = useObjectUrl(backImage);
  const frontUrl = useObjectUrl(frontImage);
  const spineUrl = useObjectUrl(spineImage);

  const borderMm = (borderThicknessPx / dpi) * MM_PER_INCH;
  const borderPreviewPx =
    borderMode === "none" || borderThicknessPx <= 0
      ? 0
      : Math.max(1, borderMm * mmToPx);
  const spineWidthPx = preset.spineWidthMm * mmToPx;
  const sideWidthPx = ((preset.totalWidthMm - preset.spineWidthMm) / 2) * mmToPx;
  const sideWidthMm = (preset.totalWidthMm - preset.spineWidthMm) / 2;
  const outerShadow =
    borderMode !== "none" && borderPreviewPx > 0 && borderColor
      ? `0 0 0 ${borderPreviewPx}px ${borderColor}`
      : "none";

  return (
    <div
      ref={wrapRef}
      className="w-full h-full flex flex-col items-center justify-center min-h-0 min-w-0"
      style={{ padding: `${padding}px` }}
    >
      <div
        ref={labelsRef}
        className="mb-5"
        style={{ width: stageWidth > 0 ? stageWidth : "100%" }}
      >
        <div className="grid grid-cols-3 text-xs font-medium text-slate-600 whitespace-nowrap">
          <div className="text-left">
            Back · {sideWidthMm.toFixed(1)} × {preset.heightMm} mm
          </div>
          <div className="text-center">Spine · {preset.spineWidthMm} mm</div>
          <div className="text-right">
            Front · {sideWidthMm.toFixed(1)} × {preset.heightMm} mm
          </div>
        </div>
      </div>

      <div
        className="relative"
        style={{
          width: stageWidth,
          height: stageHeight,
          boxShadow: outerShadow,
          background: fit === "fit" ? fitBackground : "white",
        }}
      >
        <div
          className="absolute inset-0 grid"
          style={{
            gridTemplateColumns: `${sideWidthMm}fr ${preset.spineWidthMm}fr ${sideWidthMm}fr`,
            gridTemplateRows: "100%",
          }}
        >
          <div style={{ height: "100%", position: "relative" }}>
            <SectionImage
              url={backUrl}
              fit={fit}
              placeholder="back cover"
              onChange={onSelectBack}
            />
            {onSelectBack && (
              <DropOverlay
                globalDragging={isDraggingFile}
                label="back cover"
                onSelectFile={onSelectBack}
              />
            )}
          </div>
          <div style={{ height: "100%", position: "relative" }} className="hover:z-10">
            {spineUrl ? (
              <SectionImage
                url={spineUrl}
                fit={fit}
                placeholder="spine image"
                onChange={onSelectSpine}
              />
            ) : (
              <SpinePresetPreview
                preset={spinePreset}
                title={spineTitle}
                widthPx={spineWidthPx}
                heightPx={stageHeight}
                bg={spineBg}
                textColor={spineTextColor}
                textAlign={spineTextAlign}
              />
            )}
            {onSelectSpine && (
              <DropOverlay
                globalDragging={isDraggingFile}
                label="spine"
                onSelectFile={onSelectSpine}
              />
            )}
          </div>
          <div style={{ height: "100%", position: "relative" }}>
            <SectionImage
              url={frontUrl}
              fit={fit}
              placeholder="front cover"
              onChange={onSelectFront}
            />
            {showFrontPresetImage &&
              (spinePreset === "ps2" || spinePreset === "xbox") &&
              (() => {
                const key = spinePreset as SpinePresetImageKey;
                const url = getSpinePresetImageUrl(key, "front");
                const ar = getSpinePresetImageAspectRatio(key, "front");
                const scale = sideWidthPx / ((sideWidthMm * dpi) / MM_PER_INCH);
                const previewWideningPx = frontImageWidening > 0 ? frontImageWidening * scale : 0;
                const previewSeparatorPx =
                  key === "ps2" && showFrontSeparator ? Math.max(1, 4 * scale) : 0;
                const imgHeightPx = sideWidthPx / ar;
                const blockHeightPx = imgHeightPx + previewWideningPx * 2;
                return (
                  <>
                    <div
                      className="pointer-events-none absolute left-0 top-0 w-full select-none"
                      style={{
                        height: blockHeightPx,
                        background: previewWideningPx > 0 ? "#000000" : "transparent",
                      }}
                    >
                      <img
                        src={url}
                        alt=""
                        draggable={false}
                        className="pointer-events-none absolute left-0 w-full select-none"
                        style={{
                          top: previewWideningPx,
                          height: imgHeightPx,
                        }}
                      />
                    </div>
                    {previewSeparatorPx > 0 && (
                      <div
                        className="pointer-events-none absolute left-0 w-full select-none"
                        style={{
                          top: blockHeightPx,
                          height: previewSeparatorPx,
                          background: "#ffffff",
                        }}
                      />
                    )}
                  </>
                );
              })()}
            {onSelectFront && (
              <DropOverlay
                globalDragging={isDraggingFile}
                label="front cover"
                onSelectFile={onSelectFront}
              />
            )}
          </div>
        </div>

        {borderMode === "sections" && borderPreviewPx > 0 && (
          <>
            <div
              className="absolute top-0 bottom-0"
              style={{
                left: sideWidthPx,
                width: borderPreviewPx,
                transform: `translateX(-${borderPreviewPx / 2}px)`,
                background: borderColor,
              }}
            />
            <div
              className="absolute top-0 bottom-0"
              style={{
                left: sideWidthPx + spineWidthPx,
                width: borderPreviewPx,
                transform: `translateX(-${borderPreviewPx / 2}px)`,
                background: borderColor,
              }}
            />
          </>
        )}
      </div>
    </div>
  );
}
